updated mysensors to v2.1.0

diff --git a/sensors_network/lib/MySensors/configure b/sensors_network/lib/MySensors/configure
--- a/sensors_network/lib/MySensors/configure
+++ b/sensors_network/lib/MySensors/configure
@@ -14,10 +14,15 @@ Help:
 Building options:
     --soc=[BCM2835|BCM2836|AM33XX|A10|A13|A20|H3]
                                 SoC type to be used. [configure autodetected]
-    --cpu-flags=<CXXFLAGS>      CPU defining/optimizing flags to be used. [configure autodetected]
-    --extra-cxxflags=<CXXFLAGS> Extra C flags passed to C/C++ compilation. []
+    --cpu-flags=<CPUFLAGS>      CPU defining/optimizing flags to be used. [configure autodetected]
+    --extra-cflags=<CFLAGS>     Extra C flags passed to C compilation. []
+    --extra-cxxflags=<CXXFLAGS> Extra C++ flags passed to C++ compilation. []
     --extra-ldflags=<LDFLAGS>   Extra C flags passed to linking. []
+    --c_compiler=<CC>           C compiler. [arm-linux-gnueabihf-gcc][gcc]
     --cxx_compiler=<CXX>        C++ compiler [arm-linux-gnueabihf-g++][g++]
+    --build-dir=<DIR>           Compiler directory to store object files. [build]
+    --bin-dir=<DIR>             Compiler directory to store binary files. [bin]
+    --arduino-lib-dir=<DIR>     Arduino library directory.
     --no-clean                  Don't clean previous build artifacts.
 
 Installation options:
@@ -48,12 +53,16 @@ MySensors options:
                                 MQTT publish topic prefix.
     --my-mqtt-subscribe-topic-prefix=<PREFIX>
                                 MQTT subscribe topic prefix.
-    --my-transport=[none|nrf24|rs485]
+    --my-transport=[none|nrf24|rs485|rfm95]
                                 Transport type, set to none to disable transport feature. [nrf24]
     --my-rf24-channel=<0-125>   RF channel for the sensor net, 0-125. [76]
     --my-rf24-pa-level=[RF24_PA_MAX|RF24_PA_LOW]
                                 RF24 PA level. [RF24_PA_MAX]
     --my-rf24-irq-pin=<PIN>     Pin number connected to nRF24L01 IRQ pin.
+    --my-rf24-encryption-enabled
+                                Enables RF24 encryption.
+                                All nodes and gateway must have this enabled, and all must be
+                                personalized with the same AES key
     --my-rx-message-buffer-size=<SIZE>
                                 Buffer size for incoming messages when using rf24 interrupts. [20]
     --my-rs485-serial-port=<PORT>
@@ -66,6 +75,15 @@ MySensors options:
     --my-leds-rx-pin=<PIN>      Receive LED pin.
     --my-leds-tx-pin=<PIN>      Transmit LED pin.
     --my-leds-blinking-inverse  Inverse the blinking feature.
+    --my-signing=[none|software]
+                                Message signing. [none]
+    --my-signing-debug          Enable signing related debug.
+    --my-signing-request-signatures
+                                Enable signature request from nodes that in turn requested
+                                gateway signature.
+    --my-signing-request-gw-signatures-from-all
+                                Require all nodes in the network to sign messages sent to the
+                                gateway.
 
 EOF
 }
@@ -90,7 +108,6 @@ function detect_machine {
     fi
     local soc="unknown"
     local tp="unknown"
-    local rev="unknown"
 
     if [ -z "$cpu" ]; then
         cpu="unknown"
@@ -101,13 +118,12 @@ function detect_machine {
         soc="BCM2835"
         if [[ $machine == "Raspberry"* ]]; then
             tp="RPi"
-            rev=($(detect_rpi_revision))
         fi
         ;;
     BCM2709)
         soc="BCM2836"
         if [[ $machine == "Raspberry"* ]]; then
-            rev=($(detect_rpi_revision))
+            local rev=($(detect_rpi_revision))
             if [[ $rev == "a02082" || $rev == "a22082" ]]; then
                 tp="RPi3"
             else
@@ -168,17 +184,17 @@ function detect_machine {
     *)
         soc="unknown"
     esac
-    echo "${soc} ${tp} ${cpu} ${rev}"
+    echo "${soc} ${tp} ${cpu}"
 }
 
 function gcc_cpu_flags {
     local soc=$1
     case $soc in
     BCM2835)
-        flags="-march=armv6zk -mtune=arm1176jzf-s -mfpu=vfp -mfloat-abi=hard -DLINUX_ARCH_RASPBERRYPI"
+        flags="-march=armv6zk -mtune=arm1176jzf-s -mfpu=vfp -mfloat-abi=hard"
         ;;
     BCM2836)
-        flags="-march=armv7-a -mtune=cortex-a7 -mfpu=neon-vfpv4 -mfloat-abi=hard -DLINUX_ARCH_RASPBERRYPI"
+        flags="-march=armv7-a -mtune=cortex-a7 -mfpu=neon-vfpv4 -mfloat-abi=hard"
         ;;
     AM33XX)
         flags="-march=armv7-a -mtune=cortex-a8 -mfpu=neon -mfloat-abi=hard"
@@ -205,8 +221,10 @@ function gcc_cpu_flags {
 debug=enable
 gateway_type=ethernet
 transport_type=nrf24
+signing=none
+signing_request_signatures=false
 
-params="SOC CXXFLAGS LDFLAGS PREFIX CXX GATEWAY_DIR INIT_SYSTEM"
+params="SOC CFLAGS CXXFLAGS CPPFLAGS LDFLAGS PREFIX CC CXX ARDUINO_LIB_DIR BUILDDIR BINDIR GATEWAY_DIR INIT_SYSTEM"
 
 for opt do
     if [ "$opt" = "-h" ] || [ "$opt" = "--help" ]; then
@@ -218,8 +236,14 @@ for opt do
     --soc=*)
         SOC="$optarg"
         ;;
+    --platform-type=*)
+        PT="$optarg"
+        ;;
     --cpu-flags=*)
         CPUFLAGS="$optarg"
+        ;;
+    --extra-cflags=*)
+        CFLAGS="$optarg"
         ;;
     --extra-cxxflags=*)
         CXXFLAGS="$optarg"
@@ -227,14 +251,32 @@ for opt do
     --extra-ldflags=*)
         LDFLAGS="$optarg"
         ;;
+    --c_compiler=*)
+        CC="$optarg"
+        ;;
     --cxx_compiler=*)
         CXX="$optarg"
+        ;;
+    --arduino-lib-dir=*)
+        ARDUINO_LIB_DIR=$optarg
+        ;;
+    --build-dir=*)
+        BUILDDIR="$optarg"
+        ;;
+    --bin-dir=*)
+        BINDIR="$optarg"
         ;;
     --no-clean*)
         NO_CLEAN="1"
         ;;
     --prefix=*)
         PREFIX="$optarg"
+        ;;
+    --exec-prefix=*)
+        PREFIX="$optarg"
+        ;;
+    --no_init_system*)
+        NO_INIT="1"
         ;;
     --gateway-dir=*)
         GATEWAY_DIR="$optarg"
@@ -247,10 +289,10 @@ for opt do
         ;;
     --my-node-id=*)
         gateway_type="none";
-        CXXFLAGS="-DMY_NODE_ID=${optarg} $CXXFLAGS"
+        CPPFLAGS="-DMY_NODE_ID=${optarg} $CPPFLAGS"
         ;;
     --my-config-file=*)
-        CXXFLAGS="-DMY_LINUX_CONFIG_FILE=\\\"${optarg}\\\" $CXXFLAGS"
+        CPPFLAGS="-DMY_LINUX_CONFIG_FILE=\\\"${optarg}\\\" $CPPFLAGS"
         ;;
     --my-transport=*)
         transport_type=${optarg}
@@ -260,74 +302,90 @@ for opt do
         transport_type=${optarg}
         ;;
     --my-serial-port=*)
-        CXXFLAGS="-DMY_LINUX_SERIAL_PORT=\\\"${optarg}\\\" $CXXFLAGS"
+        CPPFLAGS="-DMY_LINUX_SERIAL_PORT=\\\"${optarg}\\\" $CPPFLAGS"
         ;;
     --my-serial-baudrate=*)
-        CXXFLAGS="-DMY_BAUD_RATE=${optarg} $CXXFLAGS"
+        CPPFLAGS="-DMY_BAUD_RATE=${optarg} $CPPFLAGS"
         ;;
     --my-serial-is-pty*)
-        CXXFLAGS="-DMY_IS_SERIAL_PTY $CXXFLAGS"
+        CPPFLAGS="-DMY_IS_SERIAL_PTY $CPPFLAGS"
         ;;
     --my-serial-pty=*)
-        CXXFLAGS="-DMY_LINUX_SERIAL_PTY=\\\"${optarg}\\\" $CXXFLAGS"
+        CPPFLAGS="-DMY_LINUX_SERIAL_PTY=\\\"${optarg}\\\" $CPPFLAGS"
         ;;
     --my-serial-groupname=*)
-        CXXFLAGS="-DMY_LINUX_SERIAL_GROUPNAME=\\\"${optarg}\\\" $CXXFLAGS"
+        CPPFLAGS="-DMY_LINUX_SERIAL_GROUPNAME=\\\"${optarg}\\\" $CPPFLAGS"
         ;;
     --my-rf24-channel=*)
-        CXXFLAGS="-DMY_RF24_CHANNEL=${optarg} $CXXFLAGS"
+        CPPFLAGS="-DMY_RF24_CHANNEL=${optarg} $CPPFLAGS"
         ;;
     --my-rf24-pa-level=*)
-        CXXFLAGS="-DMY_RF24_PA_LEVEL=${optarg} $CXXFLAGS"
+        CPPFLAGS="-DMY_RF24_PA_LEVEL=${optarg} $CPPFLAGS"
         ;;
     --my-controller-url-address=*)
-        CXXFLAGS="-DMY_CONTROLLER_URL_ADDRESS=\\\"${optarg}\\\" $CXXFLAGS"
+        CPPFLAGS="-DMY_CONTROLLER_URL_ADDRESS=\\\"${optarg}\\\" $CPPFLAGS"
         ;;
     --my-controller-ip-address=*)
         controller_ip=`echo ${optarg//./,}`
-        CXXFLAGS="-DMY_CONTROLLER_IP_ADDRESS=${controller_ip} $CXXFLAGS"
+        CPPFLAGS="-DMY_CONTROLLER_IP_ADDRESS=${controller_ip} $CPPFLAGS"
         ;;
     --my-port=*)
-        CXXFLAGS="-DMY_PORT=${optarg} $CXXFLAGS"
+        CPPFLAGS="-DMY_PORT=${optarg} $CPPFLAGS"
         ;;
     --my-mqtt-client-id=*)
-        CXXFLAGS="-DMY_MQTT_CLIENT_ID=\\\"${optarg}\\\" $CXXFLAGS"
+        CPPFLAGS="-DMY_MQTT_CLIENT_ID=\\\"${optarg}\\\" $CPPFLAGS"
         ;;
     --my-mqtt-publish-topic-prefix=*)
-        CXXFLAGS="-DMY_MQTT_PUBLISH_TOPIC_PREFIX=\\\"${optarg}\\\" $CXXFLAGS"
+        CPPFLAGS="-DMY_MQTT_PUBLISH_TOPIC_PREFIX=\\\"${optarg}\\\" $CPPFLAGS"
         ;;
     --my-mqtt-subscribe-topic-prefix=*)
-        CXXFLAGS="-DMY_MQTT_SUBSCRIBE_TOPIC_PREFIX=\\\"${optarg}\\\" $CXXFLAGS"
+        CPPFLAGS="-DMY_MQTT_SUBSCRIBE_TOPIC_PREFIX=\\\"${optarg}\\\" $CPPFLAGS"
         ;;
     --my-rf24-irq-pin=*)
-        CXXFLAGS="-DMY_RX_MESSAGE_BUFFER_FEATURE -DMY_RF24_IRQ_PIN=${optarg} $CXXFLAGS"
+        CPPFLAGS="-DMY_RX_MESSAGE_BUFFER_FEATURE -DMY_RF24_IRQ_PIN=${optarg} $CPPFLAGS"
+        ;;
+    --my-rf24-encryption-enabled*)
+        CPPFLAGS="-DMY_RF24_ENABLE_ENCRYPTION $CPPFLAGS"
         ;;
     --my-rx-message-buffer-size=*)
-        CXXFLAGS="-DMY_RX_MESSAGE_BUFFER_SIZE=${optarg} $CXXFLAGS"
+        CPPFLAGS="-DMY_RX_MESSAGE_BUFFER_SIZE=${optarg} $CPPFLAGS"
         ;;
     --my-rs485-serial-port=*)
-        CXXFLAGS="-DMY_RS485_HWSERIAL=\\\"${optarg}\\\" $CXXFLAGS"
+        CPPFLAGS="-DMY_RS485_HWSERIAL=\\\"${optarg}\\\" $CPPFLAGS"
         ;;
     --my-rs485-baudrate=*)
-        CXXFLAGS="-DMY_RS485_BAUD_RATE=${optarg} $CXXFLAGS"
+        CPPFLAGS="-DMY_RS485_BAUD_RATE=${optarg} $CPPFLAGS"
         ;;
     --my-rs485-de-pin=*)
-        CXXFLAGS="-DMY_RS485_DE_PIN=${optarg} $CXXFLAGS"
+        CPPFLAGS="-DMY_RS485_DE_PIN=${optarg} $CPPFLAGS"
         ;;
     --my-rs485-max-msg-length=*)
-        CXXFLAGS="-DMY_RS485_MAX_MESSAGE_LENGTH=${optarg} $CXXFLAGS"
+        CPPFLAGS="-DMY_RS485_MAX_MESSAGE_LENGTH=${optarg} $CPPFLAGS"
         ;;
     --my-leds-err-pin=*)
-        CXXFLAGS="-DMY_DEFAULT_ERR_LED_PIN=${optarg} $CXXFLAGS"
+        CPPFLAGS="-DMY_DEFAULT_ERR_LED_PIN=${optarg} $CPPFLAGS"
         ;;
     --my-leds-rx-pin=*)
-        CXXFLAGS="-DMY_DEFAULT_RX_LED_PIN=${optarg} $CXXFLAGS"
+        CPPFLAGS="-DMY_DEFAULT_RX_LED_PIN=${optarg} $CPPFLAGS"
         ;;
     --my-leds-tx-pin=*)
-        CXXFLAGS="-DMY_DEFAULT_TX_LED_PIN=${optarg} $CXXFLAGS"
+        CPPFLAGS="-DMY_DEFAULT_TX_LED_PIN=${optarg} $CPPFLAGS"
         ;;
     --my-leds-blinking-inverse*)
-        CXXFLAGS="-DMY_WITH_LEDS_BLINKING_INVERSE $CXXFLAGS"
+        CPPFLAGS="-DMY_WITH_LEDS_BLINKING_INVERSE $CPPFLAGS"
+        ;;
+    --my-signing=*)
+        signing=${optarg}
+        ;;
+    --my-signing-debug*)
+        CPPFLAGS="-DMY_DEBUG_VERBOSE_SIGNING $CPPFLAGS"
+        ;;
+    --my-signing-request-signatures*)
+        signing_request_signatures=true
+        ;;
+    --my-signing-request-gw-signatures-from-all*)
+        signing_request_signatures=true
+        CPPFLAGS="-DMY_SIGNING_GW_REQUEST_SIGNATURES_FROM_ALL $CPPFLAGS"
         ;;
     *)
         echo "[WARNING] Unknown option detected:$opt, ignored"
@@ -336,7 +394,10 @@ for opt do
 done
 
 PREFIX=${PREFIX:-/usr/local}
+BUILDDIR=${BUILDDIR:-build}
+BINDIR=${BINDIR:-bin}
 GATEWAY_DIR=${GATEWAY_DIR:-${PREFIX}/bin}
+CC=${CC:-gcc}
 CXX=${CXX:-g++}
 
 if [ -z "${SOC}" ]; then
@@ -345,42 +406,71 @@ if [ -z "${SOC}" ]; then
     SOC=${info[0]}
     TYPE=${info[1]}
     CPU=${info[2]}
-    REV=${info[3]}
-    echo "[OK] machine detected: SoC=${SOC}, Type=${TYPE}, CPU=${CPU}, REV=${REV}."
+    echo "[OK] machine detected: SoC=${SOC}, Type=${TYPE}, CPU=${CPU}."
 fi
 
 if [ -z "${CPUFLAGS}" ]; then
     CPUFLAGS=$(gcc_cpu_flags $SOC)
 fi
 
-CXXFLAGS="$CPUFLAGS -Ofast -g -Wall -Wextra $CXXFLAGS"
-CFLAGS="-Ofast -g -Wall -Wextra $CFLAGS"
-
-if [[ $TYPE == "RPi2" || $TYPE == "RPi3" || $REV == "0010" ]]; then
-    CXXFLAGS+="-D__RPI_BPLUS"
+if [[ $SOC == "BCM2835" || $SOC == "BCM2836" ]]; then
+    CPPFLAGS="-DLINUX_ARCH_RASPBERRYPI $CPPFLAGS"
 fi
 
 if [[ ${debug} == "enable" ]]; then
-    CXXFLAGS="-DMY_DEBUG $CXXFLAGS"
+    CPPFLAGS="-DMY_DEBUG $CPPFLAGS"
 fi
 
-if [[ ${gateway_type} == "ethernet" ]]; then
-    CXXFLAGS="-DMY_GATEWAY_LINUX $CXXFLAGS"
+if [[ ${gateway_type} == "none" ]]; then
+    # Node mode selected
+    :
+elif [[ ${gateway_type} == "ethernet" ]]; then
+    CPPFLAGS="-DMY_GATEWAY_LINUX $CPPFLAGS"
 elif [[ ${gateway_type} == "serial" ]]; then
-    CXXFLAGS="-DMY_GATEWAY_SERIAL $CXXFLAGS"
+    CPPFLAGS="-DMY_GATEWAY_SERIAL $CPPFLAGS"
 elif [[ ${gateway_type} == "mqtt" ]]; then
-    CXXFLAGS="-DMY_GATEWAY_LINUX -DMY_GATEWAY_MQTT_CLIENT $CXXFLAGS"
+    CPPFLAGS="-DMY_GATEWAY_LINUX -DMY_GATEWAY_MQTT_CLIENT $CPPFLAGS"
+else
+    echo "Invalid gateway type."
+    echo "Aborting."
+    exit 1
 fi
 
-if [[ ${transport_type} == "nrf24" ]]; then
-    CXXFLAGS="-DMY_RADIO_NRF24 $CXXFLAGS"
+if [[ ${transport_type} == "none" ]]; then
+    # Transport disabled
+    :
+elif [[ ${transport_type} == "nrf24" ]]; then
+    CPPFLAGS="-DMY_RADIO_NRF24 $CPPFLAGS"
 elif [[ ${transport_type} == "rs485" ]]; then
-    CXXFLAGS="-DMY_RS485 $CXXFLAGS"
+    CPPFLAGS="-DMY_RS485 $CPPFLAGS"
+elif [[ ${transport_type} == "rfm95" ]]; then
+    CPPFLAGS="-DMY_RADIO_RFM95 $CPPFLAGS"
+else
+    echo "Invalid transport type."
+    echo "Aborting."
+    exit 1
+fi
+
+if [[ ${signing} == "none" ]]; then
+    # Signing disabled
+    :
+elif [[ ${signing} == "software" ]]; then
+    CPPFLAGS="-DMY_SIGNING_SOFT $CPPFLAGS"
+    if [[ ${signing_request_signatures} == true ]]; then
+        CPPFLAGS="-DMY_SIGNING_REQUEST_SIGNATURES $CPPFLAGS"
+    fi
+else
+    echo "Invalid message signing option."
+    echo "Aborting."
+    exit 1
 fi
 
 LDFLAGS="-pthread $LDFLAGS"
+CPPFLAGS="$CPUFLAGS $CPPFLAGS"
 
-if [ -x /usr/bin/systemctl ] || [ -x /bin/systemctl ]; then
+if [ "${NO_INIT}" ];  then
+    echo "[OK] no init system chosen."
+elif [ -x /usr/bin/systemctl ] || [ -x /bin/systemctl ]; then
     INIT_SYSTEM=systemd
     echo "[OK] init system detected: systemd"
 elif [ -f /etc/init.d/cron ] && [ ! -h /etc/init.d/cron ]; then
